# reference: http://www.cs.colby.edu/maxwell/courses/tutorials/maketutor/
CC = gcc
CFLAGS = -I.
DEPS = log.h timeformat.h # *.h files go here
OBJ = loglib.o timeformat.o errlog.o # *.o files go here

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

errlog: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)

debug: *.c
	$(CC) -g $^

clean:
	rm -f *.o errlog
